### PR TITLE
BEATBOX using JavaScript

### PR DESCRIPTION
**Pull request by DevrajDC**

### CODE REVIEW

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
@DevrajDC 
It is a great project, and I respect your coding skills but it a project and we need short and easy programs that cover javascript concepts for beginners.
So please add some Beginners friendly programs if possible. 😊
Happy Hacking !!

**Comment by DevrajDC** [comment]
This is a basic program only bro you can merge it. And i got your point, ill upload simple programs which anyone can understand 👍🏻

**Review by DevrajDC — COMMENTED** [review]
This is a beginner friendly code. It would be nice if you could merge it.

**Comment by Abhijay007** [comment]
simple and more beginners friendly code needed that covers some basic concepts.

Happy Hacking!!  😊

**Pull request closed without merging**
