### PR TITLE
Adding a Rock, Paper, Scissors Game.

### PR DESCRIPTION
**Pull request by GriffinMLN**
Hey :) I added a beginner friendly coded Rock, Paper, Scissors Game made with HTML/Javascript

### CODE REVIEW

**Comment by GriffinMLN** [comment]
@Abhijay007 this is definitely vanilla javascript and html! I didn't use any external libraries - do you see any?

**Review by Abhijay007 — COMMENTED** [review]
I use GitHub workflow for that the action is automated don't worry about it. Your contribution is displayed.

**Comment by GriffinMLN** [comment]
@Abhijay007 oh, good to know :)
If you decide to accept this PR, is there any chance you could add the 'hacktoberfest-accepted' label to it? Thank you in advance!

**Comment by GriffinMLN** [comment]
@Abhijay007 will this PR get merged? let me know if you need me to change something

**Review by Abhijay007 — CHANGES_REQUESTED** [review]
delete this file because this action is automated and after that will merge this pull request

**Comment by Abhijay007** [comment]
> delete this file because this action is automated and after that will merge this pull request

that readme.md file

**Pull request closed without merging**
